name: Python SCA Scan with Snyk

on: push

permissions:
  contents: read
  security-events: write  # Required to upload SARIF results to GitHub Code Scanning

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Install Snyk CLI
      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      # Step 5: Run Snyk test (fail build on high/critical issues) and generate SARIF
      - name: Snyk Test (Fail on High/Critical)
        run: snyk test --sarif-file-output=snyk.sarif --severity-threshold=high --fail-on=all
        env:
          SNYK_TOKEN: a1eb8b76-9f7f-4ff8-8fcb-e951abcdfa23

      # Step 6: Push results to Snyk Portal (SCA Dashboard)
      - name: Push results to Snyk Portal
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: a1eb8b76-9f7f-4ff8-8fcb-e951abcdfa23

      # Step 7: Upload SARIF results to GitHub Code Scanning
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
